app_back_office_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AppBackOfficeBundle:Default:index }

import_data:
    pattern: /import/data
    defaults: { _controller: AppBackOfficeBundle:Import:update }

reclamation:
    pattern: /reclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:envoyer }

listerReclamation:
    pattern: /listerReclamation
    defaults: { _controller: AppBackOfficeBundle:Reclamation:index }

repondreReclamation:
    pattern: /{id}/repondreReclamation
    defaults: { _controller: AppBackOfficeBundle:Reclamation:repondre }
