app_back_office_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AppBackOfficeBundle:Default:index }

update:
    pattern: /import/data
    defaults: { _controller: AppBackOfficeBundle:Import:update }
