app_back_office_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AppBackOfficeBundle:Default:index }

import_data:
    pattern: /import/data
    defaults: { _controller: AppBackOfficeBundle:Import:update }

admin_login:
    pattern: /login
    defaults: { _controller: AppBackOfficeBundle:SecurityPointAccess:login }

admin_login_check:
    pattern:   /login_check
    
admin_logout:
    path:   /logout
