app_back_office:
    resource: "@AppBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /back-office

AppBackOfficeBundle_type-demande:
        resource: "@AppBackOfficeBundle/Resources/config/routing/typedemande.yml"
        prefix:   /back-office/type-demande


app_back_office:
    resource: "@AppBackOfficeBundle/Resources/config/routing/typereclamation.yml"
    prefix:   /type-reclamation

