app_front_office_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AppFrontOfficeBundle:Default:index }

reclamationEtud:
    pattern: /reclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:envoyer }

listerReclamationEtud:
    pattern: /listerReclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:index }

showReclamationEtud:
    pattern: /{id}/showReclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:show }
